/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.banyaibalazs.awesomeapplication

import io.appium.java_client.MobileElement
import io.appium.java_client.android.AndroidDriver
import io.appium.java_client.remote.MobileCapabilityType
import org.junit.Before
import org.openqa.selenium.By
import org.openqa.selenium.remote.DesiredCapabilities
import java.net.URL
import java.util.concurrent.TimeUnit
import kotlin.test.Test

class BasicKotlinTest {

    companion object {
        val BALAZS_MOTO_NAME = "ZY223HRX2L"
    }

    val app = "${System.getProperty("user.dir")}/build/app-debug.apk"
    val host = URL("http://127.0.0.1:4723/wd/hub")

    lateinit var driver: AndroidDriver<MobileElement>

    @Before
    fun setUp() {
        val capabilities = DesiredCapabilities().apply {
            setCapability(MobileCapabilityType.PLATFORM_NAME, "Android")
            setCapability(MobileCapabilityType.APP, app)
            setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2")
            setCapability(MobileCapabilityType.DEVICE_NAME, BALAZS_MOTO_NAME)
        }

        driver = AndroidDriver(host, capabilities)
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS)
    }

    @Test
    fun testWelcome() {
        driver
            .findElement(By.id("com.banyaibalazs.awesomeapplication:id/welcome"))
            .click()

        driver
            .findElement(By.id("android:id/button1"))
            .click()
    }
}
